services:
  mu_mssql:
    image: chaudevops/mu-db:latest
    container_name: mu_mssql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MuOnline@DevOps2024!
    volumes:
      - mssql_data:/var/opt/mssql/data
    networks:
      - mu-network

volumes:
  mssql_data:

networks:
  mu-network:
    external: true
    